### PR TITLE
Fix imports

### PR DESCRIPTION
**Pull request by JamieMagee**
Convert to Python 3 style. Also fix some print statements

### CODE REVIEW

**Comment by sanderroosendaal** [comment]
Are we keeping the Python 2 backwards compatibility?

**Comment by JamieMagee** [comment]
Yeah, this style of referencing imports is backwards compatible with Python 2.

**Comment by sanderroosendaal** [comment]
How about the change from warnings to logging?

**Comment by JamieMagee** [comment]
That is also backwards compatible. See [here](https://docs.python.org/2/library/logging.html)

**Pull request merged**
